<?php

namespace App\AI\DTO;

/**
 * Data Transfer Object representing a standardized response from an AI provider.
 */
class AIResponse
{
    /**
     * @param string $content The text content generated by the AI.
     * @param string $model The model used to generate the response.
     * @param int|null $promptTokens Number of tokens in the prompt.
     * @param int|null $completionTokens Number of tokens in the completion.
     * @param int|null $totalTokens Total tokens used.
     * @param array $rawResponse The raw response from the provider, useful for debugging or provider-specific data.
     */
    public function __construct(
        public readonly string $content,
        public readonly string $model,
        public readonly ?int $promptTokens = null,
        public readonly ?int $completionTokens = null,
        public readonly ?int $totalTokens = null,
        public readonly array $rawResponse = []
    ) {
    }
}
